import Link from "next/link";

export default function Guide() {
  return <main className="guide"><header><Link className="brand" href="/" dir="ltr">TraderLab <span>/ SETUP</span></Link><Link className="button" href="/">بازگشت به اتاق کنترل</Link></header>
    <div className="eyebrow mono">LOCAL EA → PUBLISHER → DATABASE → DASHBOARD</div><h1>راه‌اندازی مشاهدهٔ زنده</h1><p>وب‌سایت روی Vercel اجرا می‌شود؛ EA و ناشر لاگ روی کامپیوتر یا VPS ویندوزی اجرای MetaTrader باقی می‌مانند. هیچ سفارش یا فرمان معاملاتی از این اتصال ارسال نمی‌شود.</p>
    <section><h2>۱. دیپلوی داشبورد</h2><ol><li>یک پروژهٔ Vercel بساز و مخزن TraderLab را متصل کن.</li><li>Root Directory را <code>web</code> و Framework را Next.js قرار بده.</li><li>Build Command برابر <code>npm run build</code> است. Node باید ۲۲ یا جدیدتر باشد.</li><li>ابتدا Preview بساز. بدون تنظیمات اتصال فقط نمونهٔ ساختگی و فایل محلی قابل مشاهده‌اند.</li></ol><a className="external" href="https://vercel.com/docs/frameworks/full-stack/nextjs" target="_blank" rel="noreferrer">مستندات Next.js روی Vercel</a></section>
    <section><h2>۲. دیتابیس و دسترسی خصوصی</h2><p>از Marketplace پروژه یک Neon PostgreSQL متصل کن. رویدادها در دیتابیس دائمی ذخیره می‌شوند.</p><ul><li><code>DATABASE_URL</code>: آدرس اتصال Neon.</li><li><code>TRADERLAB_INGEST_KEY</code>: کلید تصادفی مستقل با حداقل ۳۲ کاراکتر، فقط برای ناشر.</li><li><code>TRADERLAB_SESSION_SECRET</code>: یک مقدار تصادفی دیگر با حداقل ۳۲ کاراکتر.</li><li><code>TRADERLAB_VIEWER_PASSWORD</code>: رمز خصوصی مشاهده با حداقل ۱۲ کاراکتر.</li></ul><p>این چهار مقدار را در Environment Variables پروژه قرار بده. هیچ‌کدام نباید NEXT_PUBLIC باشند یا در Git، چت یا لاگ چاپ شوند. برای راه‌اندازی محلی آن‌ها را در web/.env.local ذخیره کن؛ فایل از Git کنار گذاشته شده است.</p><pre>{"cd D:\\Github\\TraderLab\\web\nnpm run db:setup"}</pre><p>این دستور جدول‌ها و تابع دریافت رویداد را از web/db/schema.sql نصب می‌کند. همان SQL را می‌توان در SQL Editor دیتابیس اجرا کرد. سپس پروژه را دوباره دیپلوی کن.</p><a className="external" href="https://vercel.com/docs/marketplace-storage" target="_blank" rel="noreferrer">راهنمای دیتابیس‌های Marketplace</a></section>
    <section><h2>۳. ثبت رویداد در MT5</h2><p>EA را در MetaEditor کامپایل و روی چارت Demo نماد تنظیم‌شده اجرا کن. برای هر اجرا نام فایل تازه بده. اختلاف زمان سرور با UTC باید صریح تنظیم شود؛ در غیر این صورت زمان رویدادها نامشخص می‌ماند.</p><p>مسیر فایل داخل Data Folder ترمینال و پوشهٔ MQL5/Files است. هنگام تغییر اختلاف UTC بروکر یک ثبت تازه شروع کن. EA فعلی فقط ثبت و تشخیص دارد؛ ورود خودکار و تطبیق معاملات بروکر هنوز پیاده‌سازی نشده‌اند.</p></section>
    <section><h2>۴. روشن‌کردن ناشر محلی</h2><p>کلید ناشر را در متغیر محیطی TRADERLAB_INGEST_KEY همان ویندوز تنظیم کن. سپس این دستور یک‌خطی را با مسیر فایل، URL دیپلوی و نماد واقعی بروکر اجرا کن:</p><pre>{"python tools/publish_events.py --file \"C:/actual-terminal/MQL5/Files/TraderLab-run01.jsonl\" --url \"https://your-dashboard.vercel.app\" --run \"demo-20261005-01\" --bot \"mt5-demo-01\" --label \"Demo capture 01\" --source native --symbol XAUUSD --checkpoint \"work/publisher/demo-20261005-01.json\""}</pre><p>برای هر فایل تازه، run و checkpoint تازه بده. ناشر فقط خط کامل را می‌فرستد و پس از تأیید سرور پیش می‌رود؛ اتصال مجدد رویداد تکراری نمی‌سازد. با Ctrl+C متوقف می‌شود.</p><p>برای گزارش شبیه‌سازی مسیر events.jsonl را با source برابر paper و گزینهٔ --once استفاده کن. شبیه‌سازی به عنوان معاملهٔ واقعی برچسب نمی‌خورد.</p></section>
    <section><h2>۵. مشاهده و بازپخش</h2><p>در داشبورد «اتصال زنده» را انتخاب و با رمز مشاهده وارد شو. آخرین ۳۰ اجرا قابل انتخاب‌اند. رویدادها هر ۳ ثانیه دریافت می‌شوند؛ ناشر هر ۱۰ ثانیه heartbeat می‌فرستد. وضعیت اتصال ناشر و زمان آخرین رویداد جدا هستند. توقف بازپخش، EA را متوقف نمی‌کند.</p><p>این نسخه حداکثر ۲۰٬۰۰۰ رویداد هر اجرا را در مرورگر نمایش می‌دهد و رسیدن به سقف را اعلام می‌کند. دیتابیس رویدادهای بعدی را حفظ می‌کند؛ صفحه‌بندی و تجمیع اجراهای طولانی مرحلهٔ بعد است. چارت فقط کندل‌های دریافت‌شده را نمایش می‌دهد و مرز نامشخص BOS/OB را حدس نمی‌زند.</p></section>
    <section><h2>نمایش داده چه چیزی را ثابت می‌کند؟</h2><p>«ناشر متصل» یعنی heartbeat دریافت شده؛ «رویداد تازه» یعنی لاگ رسیده است. واقعی‌بودن منشأ داده صرفاً از اتصال قابل اثبات نیست. سود paper، سود حساب بروکر یا نتیجهٔ بک‌تست تاریخی نیست. چارت با <a className="external" href="https://www.tradingview.com/" target="_blank" rel="noreferrer">TradingView Lightweight Charts</a> ساخته شده است.</p></section>
  </main>;
}

